project 'wallet.xcodeproj'

# Uncomment the next line to define a global platform for your project
  platform :ios, '10.0'

target 'GSEWallet' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  pod 'MBProgressHUD', '~> 1.1.0'
  pod 'IGListKit', '~> 3.0'
  pod 'GoogleAnalytics'
  pod 'FSLineChart'
  pod 'Stripe', '~> 14.0.0'
  pod 'Alamofire', '~> 4.7.3'
  pod 'Toast', '~> 4.0.0'
end
